name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # 升级checkout到v4

    - name: Set up JDK 18
      uses: actions/setup-java@v3  # 升级java setup到v3
      with:
        java-version: '18'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3  # 升级android setup到v3

    - name: Accept licenses
      run: |
        yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses
        $ANDROID_HOME/tools/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;34.0.0"

    - name: Build APK
      run: |
        chmod +x gradlew
        ./gradlew assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v4  # 关键修改：升级到v4版本
      with:
        name: app-release
        path: app/build/outputs/apk/release/*.apk